type Query {
  hello: String!
  users: [User]
  workers(isWorking: Boolean): [User]
  roles: [Role!]
  user(id: ID): User
  persons: [Person]
}
type Mutation {
  addUser(input: addUserInput): User
}

type Subscription {
  newUser: User
}
# union SearchInfo = User | Person

interface Person {
  id: ID!
  name: String
  age: Int
}

type User implements Person {
  id: ID!
  name: String
  age: Int
  isWorking: Boolean
  roles: [Role]
}

type ProblemSolver implements Person {
  id: ID!
  name: String!
  age: Int
  level: String
  codeForceNickname: String!
}

type Role {
  id: ID!
  designation: String
  methods: [String]
}


input addUserInput {
  name: String!
  age: Int
  isWorking: Boolean
  roles: [ID]
}
